apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-with-crds
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: prod
  template:
    metadata:
      name: 'app-with-crds-{{env}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/javacoder720/argocd
        targetRevision: main
        path: 'examples/02-app-with-custom-resources/overlays/{{env}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{env}}'

      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
