apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after CRDs - wave 1
spec:
  project: default

  source:
    repoURL: https://github.com/YOUR-ORG/YOUR-REPO  # UPDATE THIS
    targetRevision: main
    path: k8s/crds-argocd/examples/01-basic-crd-deployment

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
