apiVersion: v1
kind: Secret
metadata:
  name: web-app-db-secret
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  DATABASE_USER: appuser
  DATABASE_PASSWORD: changeme123
  DATABASE_URL: postgresql://appuser:changeme123@app-postgres.default.svc.cluster.local:5432/appdb
