apiVersion: data.example.com/v1
kind: Database
metadata:
  name: app-postgres
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  engine: postgres
  version: "15.3"
  storageSize: "20Gi"
