apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.data.example.com
spec:
  group: data.example.com
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
    - db
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["engine", "version"]
              properties:
                engine:
                  type: string
                  description: "Database engine"
                  enum: ["postgres", "mysql", "mongodb", "redis"]
                version:
                  type: string
                  description: "Database version (e.g., 14.5, 8.0)"
                  pattern: '^\d+\.\d+(\.\d+)?$'
                storageSize:
                  type: string
                  description: "Storage size (e.g., 10Gi, 100Gi)"
                  pattern: '^\d+[MGT]i$'
                  default: "10Gi"
                storageClass:
                  type: string
                  description: "Storage class name"
                  default: "gp3"
                backup:
                  type: object
                  description: "Backup configuration"
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    schedule:
                      type: string
                      description: "Cron schedule for backups"
                      default: "0 2 * * *"
                    retention:
                      type: integer
                      description: "Number of backups to retain"
                      minimum: 1
                      maximum: 90
                      default: 7
                highAvailability:
                  type: boolean
                  description: "Enable high availability mode"
                  default: false
                resources:
                  type: object
                  description: "Resource requirements"
                  properties:
                    cpu:
                      type: string
                      default: "500m"
                    memory:
                      type: string
                      default: "1Gi"
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Database phase"
                  enum: ["Pending", "Creating", "Running", "Failed"]
                endpoint:
                  type: string
                  description: "Database connection endpoint"
                port:
                  type: integer
                  description: "Database port"
                lastBackup:
                  type: string
                  format: date-time
                  description: "Timestamp of last successful backup"
                conditions:
                  type: array
                  items:
                    type: object
                    required: ["type", "status"]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Engine
          type: string
          jsonPath: .spec.engine
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Storage
          type: string
          jsonPath: .spec.storageSize
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Endpoint
          type: string
          jsonPath: .status.endpoint
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
