apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.data.example.com
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Install CRD first
    argocd.argoproj.io/sync-options: Delete=false  # Don't auto-delete CRD
spec:
  group: data.example.com
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
    - db
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["engine", "version"]
              properties:
                engine:
                  type: string
                  description: "Database engine"
                  enum: ["postgres", "mysql", "mongodb", "redis"]
                version:
                  type: string
                  description: "Database version"
                  pattern: '^\d+\.\d+(\.\d+)?$'
                storageSize:
                  type: string
                  description: "Storage size (e.g., 10Gi)"
                  pattern: '^\d+[MGT]i$'
                  default: "10Gi"
                backup:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    schedule:
                      type: string
                      default: "0 2 * * *"
                    retention:
                      type: integer
                      minimum: 1
                      maximum: 90
                      default: 7
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Creating", "Running", "Failed"]
                endpoint:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Engine
          type: string
          jsonPath: .spec.engine
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Storage
          type: string
          jsonPath: .spec.storageSize
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
